### ISSUE TITLE
If coordinates are not found, reverse the components and try again

### ISSUE THREAD

**Issue by mikehearn** [mikehearn/graviton-browser#22]
Right now you start an app in Graviton by specifying a Maven coordinate. There is some smartness done to make it easier:

* `com.github.spotbugs:spotbugs` without a version will select the latest version
* `com.github.spotbugs` will assume the artifact is the same as the last groupID component

But reverse DNS is a bit odd for people who aren't programmers and are used to things being the other way around. Allow apps to be started with DNS style names by reversing the components if the first attempt isn't found, then trying again:

`spotbugs.github.com` -> `com.github.spotbugs`

`tictactoe.plan99.net` -> `net.plan99.tictactoe`

**Comment by belu** [comment]
In the above example did you meant the following mapping:
`plan99.net:tictactoe -> net.plan99:tictactoe`

That is: when a Maven coordinate is given, only the first part (the groupId) should be reversed? The other parts like the artifactId, version and optional arguments stay the same.
