### ISSUE TITLE
Recently used apps picker

### ISSUE THREAD

**Issue by mikehearn** [mikehearn/graviton-browser#31]
A basic one is in place already. Still to do:

- [x] Make sure scrolling is sensible
- [ ] Keyboard shortcuts for each app.
- [ ] Artwork for apps

**Comment by belu** [comment]
Should the version of the app be displayed, too? Started different versions of SpotBugs but was then unable to distinguish between them.

**Comment by mikehearn** [comment]
When there are multiple 'pinned' versions in the history list, then yes. But mostly I hope users won't do that.

**Comment by mikehearn** [comment]
BTW I made some visual improvements to the app history picker.

**Comment by mikehearn** [comment]
Going to split this into separate issues.
